# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.6.1
group=net.litetex.mcm
java_version=21

# Common
minecraft_version=1.20
mod_name=Rabbit Pathfinding Fixed
mod_author=litetex
mod_id=rabbit_pathfinding_fix
license=Apache-2.0
credits=
description=Fixes rabbit pathfinding / MC-150224
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.16.8-hotspot

# Forge
forge_version=46.0.14
forge_loader_version_range=[46,)

# NeoForge
neoforge_version=20.2.86
neoforge_loader_version_range=[1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
